Events to trigger change in status
arinaldi/gist-uploader pull request #3
Opened 2017-05-08 17:17 UTC by arinaldi

2017-05-08 18:12 UTC, ashleymichal requested changes

2017-05-08 18:12 UTC, ashleymichal commented on accessGitHub.js
> +class MyEmitter extends EventEmitter {}
unless you're actually going to extend this, maybe just create your emitter off the base class.

2017-05-08 18:12 UTC, ashleymichal commented on gistUploader.js
>        if (filesProcessed === array.length) {
you only want to do this once so you should do it outside of your iterator.

2017-05-08 19:40 UTC, arinaldi commented on accessGitHub.js
> +class MyEmitter extends EventEmitter {}
Done.

2017-05-08 21:08 UTC, arinaldi commented on gistUploader.js
>        if (filesProcessed === array.length) {
Done.

2017-05-08 21:18 UTC, ashleymichal requested changes

2017-05-08 21:18 UTC, ashleymichal commented on gistUploader.js
> +  files.forEach((file) => {
last refactor: when you see this pattern:
```
const accumulator = {}; // or let accumulator = [];
things.forEach(thing => { ...accumulator, thingName: thing })
```
you probably have a good case for `.reduce()`

2017-05-09 14:01 UTC, arinaldi commented on gistUploader.js
> +  files.forEach((file) => {
Done.

2017-05-09 15:43 UTC, ashleymichal approved these changes

2017-05-09 21:10 UTC, merged